experiment_name: _run_hyperas_CNNtest_i1500
input_files:
  models:
    Model_L2_C2: models/Model_L2_C2.py
    Model_L2_I4C1: models/Model_L2_I4C1.py
    Model_L2_C1R4: models/Model_L2_C1R4.py
    Model_L2_SR2MR2: models/Model_L2_SR2MR2.py
    Model_L2_SR2F2: models/Model_L2_SR2F2.py
    Model_L2_MR4: models/Model_L2_MR4.py
  datasets:
    dataset_good_rsd2_merged:
      file: data/dataset_good_rsd2_merged.npz
      chunks: 1
      reverse: False


  #app specific of application
  app: "optimize_model.py"
  hparam_config: "params.yml"
  optimizer_iterations: 1500
  multi_gpu: 1
params:
  #replicates
  replicate_seed: [1235]
  random_seed: 1112
