
input_files:
  models:
     THIS_model : "models/THIS_model_input.py"
     THIS_CNN_NN_vals: "models/THIS_CNN_NN_vals_input.py"
  template : "template/THIS_model-V3.ipynb"
  datasets :
    data1 : "data/THIS_data.npz"
#default config output_dir
config_dir: "defaults"
#saving configs
output_dir: "configs"

params:
  shuffle: True
#learning rates alpha
#r = a*np.random.rand(n)
#alpha = 10 ** r
  alpha:
   a: -4
   #b: 0
   n: 1

#momentum beta
#beta = 1 - 10 ^ r
#r E [-a, -b] r.r. -3, -1
  beta:
   a: -3
   b: -1
   n: 1

  mbatch: [100]

  adam:
   beta1: 0.9
   beta2: 0.999
   epsilon: 10e-9

  epochs: 2
  dropout: [0.5]
  nFC: [10, 20, 30]
