
input_files:
  models:
   #THIS_model: "models/THIS_model_input.py"
   POC_v1_begh: ./models/POC_v1_begh.py
   POC_v1_befh: ./models/POC_v1_befh.py
   POC_v1_acgh: ./models/POC_v1_acgh.py
   POC_v1_bdfh: ./models/POC_v1_bdfh.py
   POC_v1_bdgh: ./models/POC_v1_bdgh.py
   POC_v1_aegh: ./models/POC_v1_aegh.py
   POC_v1_bcgh: ./models/POC_v1_bcgh.py
   POC_v1_bcfh: ./models/POC_v1_bcfh.py
   POC_v1_adgh: ./models/POC_v1_adgh.py
   
  template: "template/THIS_model-V2.ipynb"
    #THIS_model-V2: "models/THIS_model-V2.ipynb"

#default config output_dir
config_dir: "defaults"
#saving configs
output_dir: "configs"

params:
#learning rates alpha
#r = a*np.random.rand(n)
#alpha = 10 ** r
  alpha:
    a: -4
    #b: 0
    n: 1

#momentum beta
#beta = 1 - 10 ^ r
#r E [-a, -b] r.r. -3, -1
  beta:
    a: -3
    b: -1
    n: 1

  mbatch: [100]

  adam:
    beta1: 0.9
    beta2: 0.999
    epsilon: 10e-9

  epochs: 1
  dropout: [0.5]
  nFC: [10, 20, 30]
