experiment_name: _run_hyperas_test_callback
input_files:
  models:
    Model_C3F2dil_timeseries:
      model: models/Model_C1_param.py
      loss: mse
      metrics: coef_det_k
  datasets:
    dataset_v01: 
      file: data/data_min-system-boxcox_corrected_rsd2.npz

  #app specific of application
  app: "optimize_model.py"
  hparam_config: "params.yml"
  optimizer_iterations: 3
  multi_gpu: 1
params:
  #replicates
  replicate_seed: [1234]
  random_seed: 1111
  one_job: 1
