
input_files:
  models:
     FC_Xval : "models/THIS_model_FC.py"
  template : "template/THIS_model-V7.ipynb"
  datasets :
    data1 : "data/data_min-system-boxcox_corrected_rsd2.npz"
#default config output_dir
config_dir: "defaults"
#saving configs
output_dir: "configs"

params:
  shuffle: False
  model_load: False

  mbatch: 64 #[64,128,256]
  dropout: 0 #[0.1, 0.2, 0.3]
  epochs: 500 #500

#early stopping
  min_delta: 0.01
  patience: 30

#learning rates alpha
#r = a*np.random.rand(n)
#alpha = 10 ** r
  alpha: 0.0001
#   a: -3
#   #b: 0
#   n: 1 #8

#momentum beta -> adam beta1
#beta = 1 - 10 ^ r
#r E [-a, -b] r.r. -3, -1
  beta: 0.9
#   a: -3
#   b: 0
#   n: 1 #6

  beta2: 0.999
#   a: -4
#   b: -1
#   n: 1 #6

  epsilon: 1e-8 #[1e-2,1e-4,1e-6,1e-8]
  decay: 0 #[0,0.0000001,0.00001,0.001]

#learning rate scheduler
  lrs : False
  lrs_drop: 0 #[0.25,0.5,0.75,0.9]
  lrs_treshold: 10 #[0,10,20,30]
  lrs_epoch_drop: 10

  replicate: [1,2,3]
