input_files:
  models:
    Model_C1 : "models/Model_C1_commet.py"
    Model_C2 : "models/Model_C2_commet.py"
    Model_C3 : "models/Model_C3_commet.py"
  datasets:
    dataset_good_rsd1_3utr:
      file : "data/dataset_good_rsd1_3utr.npz"
      chunks : 1
      reverse : T

    dataset_good_rsd2_3utr:
      file: "data/dataset_good_rsd2_3utr.npz"
      chunks: 1
      reverse: False


  #app specific of application
  app : "optimize_model.py"
  hparam_config: "params.pcs"
  optimizer_iterations: 5
  experiment_suffix: "run1"
  multi_gpu: 1
params:
  #replicates
  replicate_seed: [1234]
  random_seed: 1111
